<a href="https://colab.research.google.com/github/mjk022/portfolio/blob/main/folium_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install folium

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: folium in /usr/local/lib/python3.9/dist-packages (0.14.0)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.9/dist-packages (from folium) (3.1.2)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.9/dist-packages (from folium) (0.6.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from folium) (1.22.4)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from folium) (2.27.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.9/dist-packages (from jinja2>=2.9->folium) (2.1.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->folium) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests->folium) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->folium) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->folium) (1.26.15)

In [ ]:
import folium

In [ ]:
folium.Map()

In [ ]:
# 위도
latitude = 37.607363
# 경도
longitude = 127.042933

# 지도 뿌리기
### folium.Map(location=[latitude, longitude],
###               zoom_start=17,  # 제일 키운게 18이다.
###              width=750,
###               height=500
###              )

In [ ]:
m = folium.Map(location=[latitude, longitude],
               zoom_start=18,
               width=750,
               height=500
              )
m

#이거는 지도를 뿌리고 내가 원하는 걸 그리는 거다.

In [ ]:
m.save('UNIV.html')

# 지도 위에 표시하기
    folium.Marker([위도,경도],
                   popup="동덕여자대학교", #옵션으로
                   tooltip="동덕여자대학교 인문관")

In [ ]:
m = folium.Map(location=[latitude, longitude],
               zoom_start=18,
               width=750,
               height=500
              )

folium.Marker([latitude, longitude],
              popup="동덕여자대학교", #옵션으로
              tooltip="동덕여자대학교 인문관").add_to(m) # 내가 만들어 놓은 지도 m위레다가 이 작업 해줘.
m

In [ ]:
folium.Marker([latitude, longitude],
              popup="동덕여자대학교", #옵션으로
              tooltip="동덕여자대학교 인문관").add_to(m) # 내가 만들어 놓은 지도 m위레다가 이 작업 해줘.
m

In [ ]:
import pandas as pd

In [ ]:
location = "https://data.smartdublin.ie/dataset/33ec9fe2-4957-4e9a-ab55-c5e917c7a9ab/resource/2dec86ed-76ed-47a3-ae28-646db5c5b965/download/dublin.csv"
#자전거 대여소
bike_station_locations = pd.read_csv(location)

In [ ]:
bike_station_locations

,Number,Name,Address,Latitude,Longitude
0,42,SMITHFIELD NORTH,Smithfield North,53.349562,-6.278198
1,30,PARNELL SQUARE NORTH,Parnell Square North,53.353462,-6.265305
2,54,CLONMEL STREET,Clonmel Street,53.336021,-6.262980
3,108,AVONDALE ROAD,Avondale Road,53.359405,-6.276142
4,56,MOUNT STREET LOWER,Mount Street Lower,53.337960,-6.241530
...,...,...,...,...,...
105,39,WILTON TERRACE,Wilton Terrace,53.332383,-6.252717
106,83,EMMET ROAD,Emmet Road,53.340714,-6.308191
107,92,HEUSTON BRIDGE (NORTH),Heuston Bridge (North),53.347802,-6.292432
108,21,LEINSTER STREET SOUTH,Leinster Street South,53.342180,-6.254485
109,88,BLACKHALL PLACE,Blackhall Place,53.348800,-6.281637

In [ ]:
bike_station_locations = bike_station_locations[["Latitude", "Longitude", "Name"]] #위도, 경도, 이름
bike_station_locations

      Latitude  Longitude                    Name
0    53.349562  -6.278198        SMITHFIELD NORTH
1    53.353462  -6.265305    PARNELL SQUARE NORTH
2    53.336021  -6.262980          CLONMEL STREET
3    53.359405  -6.276142           AVONDALE ROAD
4    53.337960  -6.241530      MOUNT STREET LOWER
..         ...        ...                     ...
105  53.332383  -6.252717          WILTON TERRACE
106  53.340714  -6.308191              EMMET ROAD
107  53.347802  -6.292432  HEUSTON BRIDGE (NORTH)
108  53.342180  -6.254485   LEINSTER STREET SOUTH
109  53.348800  -6.281637         BLACKHALL PLACE

[110 rows x 3 columns]

In [ ]:
map = folium.Map(location=[bike_station_locations.Latitude.mean(), bike_station_locations.Longitude.mean()], zoom_start=14, control_scale=True)
#위도와 경도의 평균 을 보여주게 지도를 보여주라. 예를 들어 경기도 유치원을 보여주고 싶으니까 경기도가 다 나오게 보여주라.

In [ ]:
map

In [ ]:
for index, location_info in bike_station_locations.iterrows(): #iterrows는 하나하나 내려가면서 돌려줘.
    folium.Marker([location_info["Latitude"], location_info["Longitude"]], popup=location_info["Name"]).add_to(map)

In [ ]:
map

In [ ]:
m = folium.Map(location=[37.607363, 127.042933], zoom_start=15, tiles="Stamen Terrain") #tiles 가 지도 종류이다.

folium.Marker(
    location=[37.607363, 127.042933],
    popup="Mt. Hood Meadows",
    icon=folium.Icon(icon="cloud"), #표시 마커도 여러 종류가 있다.
).add_to(m)

folium.Marker(
    location=[37.5999, 127.031111],
    popup="Timberline Lodge",
    icon=folium.Icon(color="green"),
).add_to(m)

folium.Marker(
    location=[37.6000, 127.02301],
    popup="Some Other Location",
    icon=folium.Icon(color="red", icon="info-sign"),
).add_to(m)


m

In [ ]:
m = folium.Map(location=[37.607363, 127.042933], tiles="Stamen Toner", zoom_start=13)

folium.Circle(
    radius=100,
    location=[37.607363, 127.042933],
    popup="The Waterfront",
    color="crimson",
    fill=False,
).add_to(m)

folium.CircleMarker(
    location=[37.607363, 127.042933],
    radius=50,
    popup="Laurelhurst Park",
    color="#3186cc",
    fill=True, # 원으로 채워준다.
    fill_color="#3186cc",
).add_to(m)


m

In [ ]:
m = folium.Map(location=[37.607363, 127.042933], tiles="Stamen Terrain", zoom_start=13)

m.add_child(folium.LatLngPopup())

m

In [ ]:
m = folium.Map(location=[37.607363, 127.042933], tiles="Stamen Terrain", zoom_start=13)

folium.Marker([37.607363, 127.042933], popup="Camp Muir").add_to(m)

m.add_child(folium.ClickForMarker(popup="Waypoint"))


m

In [ ]:
m = folium.Map(location=[37.607363, 127.042933], tiles="Stamen Terrain", zoom_start=13)

folium.Marker([37.607363, 127.042933], popup="Camp Muir").add_to(m)

m.add_child(folium.ClickForMarker(popup="Waypoint"))


m

# folium.PolyLine
## 폴리라인: 지하철 노선같은 라인을 표시하고 싶을때
## 폴리건: 구나 서울특별시 같은 큰 구역 표시하고 싶을때

In [ ]:
m = folium.Map(location=[-71.38, -73.9], zoom_start=11)   #이게 지하철 노선을 따라 가는 상권분석

trail_coordinates = [
    (-71.351871840295871, -73.655963711222626),
    (-71.374144382613707, -73.719861619751498),
    (-71.391042575973145, -73.784922248007007),
    (-71.400964450973134, -73.851042243124397),
    (-71.402411391077322, -74.050048183880477),
]


folium.PolyLine(trail_coordinates, tooltip="Coast").add_to(m)  #폴리움에 폴리라인이 있다. 저 좌표들을 집어넣으면 점들을 이어주는 선이 나타난다.

m

In [ ]:
import json

import requests

url = (
    "https://raw.githubusercontent.com/python-visualization/folium/main/examples/data"
)
vis1 = json.loads(requests.get(f"{url}/vis1.json").text)
vis2 = json.loads(requests.get(f"{url}/vis2.json").text)
vis3 = json.loads(requests.get(f"{url}/vis3.json").text)

In [ ]:
m = folium.Map(location=[46.3014, -123.7390], zoom_start=7, tiles="Stamen Terrain")

folium.Marker(
    location=[47.3489, -124.708],
    popup=folium.Popup(max_width=450).add_child(
        folium.Vega(vis1, width=450, height=250)
    ),
).add_to(m)

folium.Marker(
    location=[44.639, -124.5339],
    popup=folium.Popup(max_width=450).add_child(
        folium.Vega(vis2, width=450, height=250)
    ),
).add_to(m)

folium.Marker(
    location=[46.216, -124.1280],
    popup=folium.Popup(max_width=450).add_child(
        folium.Vega(vis3, width=450, height=250)
    ),
).add_to(m)

m